services:
  servoca-london:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servoca-london-salesite
    restart: unless-stopped
    ports:
      - "9009:80"
    networks:
      - salesite

networks:
  salesite:
    external: true
