services:
  community-short-breaks:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: community-short-breaks-salesite
    restart: unless-stopped
    ports:
      - "9039:80"
    networks:
      - salesite

networks:
  salesite:
    external: true
