services:
  benefleet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benefleet-salesite
    restart: unless-stopped
    ports:
      - "9048:80"
    networks:
      - salesite

networks:
  salesite:
    external: true
