services:
  walfinch-eastbourne:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: walfinch-eastbourne-salesite
    restart: unless-stopped
    ports:
      - "9004:80"
    networks:
      - salesite

networks:
  salesite:
    external: true
