services:
  sunbrust-house:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunbrust-house-salesite
    restart: unless-stopped
    ports:
      - "9008:80"
    networks:
      - salesite

networks:
  salesite:
    external: true
